apiVersion: v1
kind: Secret
metadata:
  name: {{ include "asapm.resourceName" . }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "asapm.resourceName" . }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
{{- if .Values.frontend.tls.enabled }}
    cert-manager.io/cluster-issuer: letsencrypt-issuer
{{- end }}
spec:
  rules:
    - host: "{{ .Values.frontend.host }}"
      http:
        paths:
          - path: {{ tpl .Values.frontend.basePathTemplate . }}
            backend:
              serviceName: {{ include "asapm.resourceName" . }}
              servicePort: {{ .Values.frontend.internalPort }}
{{- if .Values.frontend.tls.enabled }}
  tls:
    - hosts:
        - "{{ .Values.frontend.host }}"
      secretName: letsencrypt-asapm
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "asapm.resourceName" . }}
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.internalPort }}
  selector:
    app: {{ include "asapm.resourceName" . }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "asapm.resourceName" . }}
  labels:
    app: {{ include "asapm.resourceName" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "asapm.resourceName" . }}
  template:
    metadata:
      labels:
        app: {{ include "asapm.resourceName" . }}
    spec:
      containers:
        - name: {{ include "asapm.resourceName" . }}
          image: "{{ .Values.frontend.image }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.frontend.internalPort }}
          stdin: true
          env:
            - name: REACT_APP_API_URL
              value: ""
            - name: PUBLIC_URL
              value: "{{ tpl .Values.frontend.basePathTemplate . }}"
            - name: SERVICE_PORT
              value: "{{ .Values.frontend.internalPort }}"
{{- if .Values.frontend.imageCredentials.use }}
      imagePullSecrets:
        - name: {{ include "asapm.resourceName" . }}
{{- end }}