variables:
  FRONTEND_IMAGE: $REGISTRY/yakubov/asapm/frontend:$CI_COMMIT_SHORT_SHA
  FRONTEND_IMAGE_STATIC: $REGISTRY/yakubov/asapm/frontend
  FRONTEND_URL: http://gitlab-ci-node1.desy.de/${CI_PROJECT_NAME}-${CI_PROJECT_ID}-deploy-for-tests-${CI_COMMIT_SHORT_SHA}/asapm/

build_frontend_dev:
  stage: build_dev
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --cache=true --context $CI_PROJECT_DIR/frontend --dockerfile $CI_PROJECT_DIR/frontend/Dockerfile --target base --destination $FRONTEND_IMAGE
  tags:
    - kubernetes-executor

unit_tests_frontend:
  variables:
    GIT_CHECKOUT: "false"
  stage: unit_tests
  image:
    name: $FRONTEND_IMAGE
    entrypoint: [""]
  before_script:
    - cd /src
  script:
    - npm run test
  tags:
    - kubernetes-executor

build_frontend:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --cache=true --context $CI_PROJECT_DIR/frontend --dockerfile $CI_PROJECT_DIR/frontend/Dockerfile --destination $FRONTEND_IMAGE
  tags:
    - kubernetes-executor

deploy-frontend:
  stage: deploy
  image:
    name: eosc-pan-git.desy.de:5555/k8s/helm-ci-image:latest
    entrypoint: [""]
  script:
    - DYNAMIC_ENVIRONMENT_URL=$(echo ${FRONTEND_URL})
    - echo "DYNAMIC_ENVIRONMENT_URL=$DYNAMIC_ENVIRONMENT_URL" >> deploy.env    # Add the value to a dotenv file.
    - helm install
      --set frontend.image=${FRONTEND_IMAGE}
      --set resourceSuffix="-${CI_COMMIT_SHORT_SHA}"
      --set frontend.imageCredentials.use=true
      --set frontend.imageCredentials.registry=eosc-pan-git.desy.de:5555
      --set frontend.imageCredentials.username=${REGISTRY_USERNAME}
      --set frontend.imageCredentials.password=${REGISTRY_PASS}
      --set frontend.host="*.desy.de"
      --wait --timeout 10m0s
      asapm-frontend-${CI_COMMIT_SHORT_SHA} frontend/helm/asapm-frontend
  artifacts:
    reports:
      dotenv: deploy.env
  environment:
    name: deploy-for-tests-frontend
    url: ${DYNAMIC_ENVIRONMENT_URL}
    on_stop: destroy-frontend
    kubernetes:
  tags:
    - kubernetes-executor

int_tests_frontend:
  stage: integration_tests
  image:
    name: curlimages/curl
    entrypoint: [""]
  script:
    - curl --fail ${FRONTEND_URL} | grep react
  tags:
    - kubernetes-executor

destroy-frontend:
  stage: destroy_deployments
  image:
    name: eosc-pan-git.desy.de:5555/k8s/helm-ci-image:latest
    entrypoint: [""]
  script:
    - helm uninstall -n $KUBE_NAMESPACE asapm-frontend-${CI_COMMIT_SHORT_SHA}
  environment:
      name: deploy-for-tests-frontend
      action: stop
      kubernetes:
  when: always
  tags:
    - kubernetes-executor

