mode = os.getenv('TILT_MODE')
targetHost = os.getenv('TILT_TARGET_HOST')


repo = local_git_repo('..')

k8s_yaml(helm('helm/asapm-frontend', set=['frontend.host='+targetHost]))
allow_k8s_contexts('guest-k8s')
watch_file('helm/asapm-frontend')
watch_file('helm/asapm-frontend/templates')

docker_build('yakser/asapm-frontend', '.',
  live_update=[
    # when package.json changes, we need to do a full build
    fall_back_on(['package.json', 'package-lock.json']),
    # Map the local source code into the    container under /src
    sync('.', '/src'),
  ],
  target='' if mode == 'prod' else 'base' )


