stages:
  - build_dev
  - lint
  - unit_tests
  - build
  - deploy
  - integration_tests
  - destroy_deployments

variables:
  REGISTRY: gitlab.desy.de:5555


include:
  - local: '/frontend/.gitlab-ci.yml'
  - local: '/api_server/.gitlab-ci.yml'
