// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Meta struct {
	ID           string                 `json:"id"`
	Text         string                 `json:"text"`
	CustomValues map[string]interface{} `json:"customValues"`
}

type NewMeta struct {
	Text         string                 `json:"text"`
	CustomValues map[string]interface{} `json:"customValues"`
}
