apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: asapm-api-server
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: {{ .Values.apiServer.host }}
      http:
        paths:
          - path: /{{ .Release.Namespace }}/asapm/api
            backend:
              serviceName: asapm-api-server
              servicePort: {{ .Values.apiServer.internalPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: asapm-api-server
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{ .Values.apiServer.internalPort }}
  selector:
    app: asapm-api-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: asapm-api-server
  labels:
    app: asapm-api-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: asapm-api-server
  template:
    metadata:
      labels:
        app: asapm-api-server
    spec:
      containers:
        - name: asapm-api-server
          image: "yakser/asapm-api-server"
          ports:
            - containerPort: {{ .Values.apiServer.internalPort }}
          env:
            - name: ASAPM_API_PORT
              value:  "{{ .Values.apiServer.internalPort }}"
            - name: ASAPM_API_ENDPOINT
              value:  "/{{ .Release.Namespace }}{{ .Values.apiServer.endpoint }}"

