apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "asapm.resourceName" . }}
  labels:
    app: {{ include "asapm.resourceName" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "asapm.resourceName" . }}
  template:
    metadata:
      labels:
        app: {{ include "asapm.resourceName" . }}
    spec:
      volumes:
        - name: {{ include "asapm.resourceName" . }}-config
          configMap:
            name: {{ include "asapm.resourceName" . }}-config
        - name: {{ include "asapm.resourceName" . }}-pubkey
          secret:
            secretName: {{ include "asapm.resourceName" . }}-pubkey
      containers:
        - name: {{ include "asapm.resourceName" . }}
          image: "{{ .Values.apiServer.image }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.apiServer.internalPort }}
          volumeMounts:
            - mountPath: "/etc/asapm"
              name: {{ include "asapm.resourceName" . }}-config
            - mountPath: "/etc/asapm/keys"
              name: {{ include "asapm.resourceName" . }}-pubkey
  {{- if .Values.apiServer.imageCredentials.use }}
      imagePullSecrets:
        - name: {{ include "asapm.resourceName" . }}
  {{- end }}
