apiVersion: v1
kind: Secret
metadata:
  name: {{ include "asapm.resourceName" . }}-pubkey
data:
  key.pub: {{ tpl (.Files.Get "config/key.pub") . | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "asapm.resourceName" . }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
