apiVersion: v1
kind: Service
metadata:
  name: {{ include "asapm.resourceName" . }}
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{ .Values.apiServer.internalPort }}
  selector:
    app: {{ include "asapm.resourceName" . }}