resourceSuffix: ""

apiServer:
  internalPort: 8080
  host: "localhost"
  image: yakser/asapm-api-server
  basePathTemplate: "/{{ .Release.Namespace }}{{ .Values.resourceSuffix}}/asapm/api"
  imageCredentials:
    use : false
    registry: quay.io
    username: someone
    password: sillyness
