resourceSuffix: ""

apiServer:
  internalPort: 8080
  host: "localhost"
  image: yakser/asapm-api-server
  basePath: "/{{ .Release.Namespace }}{{ .Values.resourceSuffix}}/asapm/api"
  dbEndpoint: "{{ .Release.Name }}-mongodb:27017"
  tls:
    enabled: false
  imageCredentials:
    use: false
    registry: quay.io
    username: someone
    password: sillyness

mongodb:
  useStatefulSet: false
  architecture: "standalone"
  auth:
    enabled: false

