resourceSuffix: ""

frontend:
  internalPort: 3000
  host: "localhost"
  image: yakser/asapm-frontend
  basePathTemplate: "/{{ .Release.Namespace }}/asapm{{ .Values.resourceSuffix }}"
  tls:
    enabled: false
  imageCredentials:
    use : false
    registry: quay.io
    username: someone
    password: sillyness
