resourceSuffix: ""

frontend:
  internalPort: 3000
  host: "localhost"
  image: yakser/asapm-frontend
  basePathTemplate: "/{{ .Release.Namespace }}{{ .Values.resourceSuffix }}/asapm"
  imageCredentials:
    use : false
    registry: quay.io
    username: someone
    password: sillyness
