variables:
  API_SERVER_IMAGE: $REGISTRY/yakubov/asapm/api_server:$CI_COMMIT_SHORT_SHA
  API_SERVER_IMAGE_STATIC: $REGISTRY/yakubov/asapm/api_server
  API_SERVER_URL: http://gitlab-ci-node1.desy.de/${CI_PROJECT_NAME}-${CI_PROJECT_ID}-deploy-for-tests-${CI_COMMIT_SHORT_SHA}/asapm/api

build_api_server_dev:
  stage: build_dev
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --cache=true --context $CI_PROJECT_DIR/api_server --dockerfile $CI_PROJECT_DIR/api_server/Dockerfile --target base --destination $API_SERVER_IMAGE
  tags:
    - kubernetes-executor

unit_tests_api_server:
  variables:
    GIT_CHECKOUT: "false"
  stage: unit_tests
  image:
    name: $API_SERVER_IMAGE
    entrypoint: [""]
  before_script:
    - cd /app/src
  script:
    - go test ./...
  tags:
    - kubernetes-executor

build_api_server:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --cache=true --context $CI_PROJECT_DIR/api_server --dockerfile $CI_PROJECT_DIR/api_server/Dockerfile --destination $API_SERVER_IMAGE
  tags:
    - kubernetes-executor

deploy-api-server:
  stage: deploy
  image:
    name: eosc-pan-git.desy.de:5555/k8s/helm-ci-image:latest
    entrypoint: [""]
  script:
    - DYNAMIC_ENVIRONMENT_URL=$(echo ${API_SERVER_URL})
    - echo "DYNAMIC_ENVIRONMENT_URL=$DYNAMIC_ENVIRONMENT_URL" >> deploy.env    # Add the value to a dotenv file.
    - helm install
      --set apiServer.image=${API_SERVER_IMAGE}
      --set resourceSuffix="-${CI_COMMIT_SHORT_SHA}"
      --set apiServer.imageCredentials.use=true
      --set apiServer.imageCredentials.registry=eosc-pan-git.desy.de:5555
      --set apiServer.imageCredentials.username=${REGISTRY_USERNAME}
      --set apiServer.imageCredentials.password=${REGISTRY_PASS}
      --set apiServer.host="*.desy.de"
      --wait --timeout 1m0s
      asapm-api-server-${CI_COMMIT_SHORT_SHA} api_server/helm/asapm-api-server
  artifacts:
    reports:
      dotenv: deploy.env
  environment:
    name: deploy-for-tests-api-server
    url: ${DYNAMIC_ENVIRONMENT_URL}
    on_stop: destroy_api_server
    kubernetes:
  tags:
    - kubernetes-executor

#int_tests_frontend:
#  stage: integration_tests
#  image:
#    name: curlimages/curl
#    entrypoint: [""]
#  script:
#    - curl --fail ${FRONTEND_URL} | grep react
#  tags:
#    - kubernetes-executor
#

destroy_api_server:
  stage: destroy_deployments
  image:
    name: eosc-pan-git.desy.de:5555/k8s/helm-ci-image:latest
    entrypoint: [""]
  script:
    - helm uninstall -n $KUBE_NAMESPACE asapm-api-server-${CI_COMMIT_SHORT_SHA}
  environment:
      name: deploy-for-tests-api-server
      action: stop
      kubernetes:
  when: always
  tags:
    - kubernetes-executor

